# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "패키지"
    url = "/packages/"
    weight = 1
[[main]]
    name = "시작하기"
    url = "/start/"
    weight = 2
[[main]]
    name = "배우기"
    url = "/learn/"
    weight = 3
[[main]]
    name = "도움받기"
    url = "/help/"
    weight = 4
[[main]]
    name = "기여하기"
    url = "/contribute/"
    weight = 5
[[main]]
    name = " "
    url = "/find/"
    pre = "<i class=\"fas fa-search fa-lg\"></i>"
    weight = 6
[[main]]
    pre = "<i class=\"fab fa-github fa-lg\"></i>"
    url = "https:github.com/sulgik/tidymodels.org"
    weight = 7

